# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files and lockfile
COPY package*.json ./
COPY tsconfig.json ./

# Copy entire repository
COPY . .

# Install dependencies without running scripts (we run build explicitly)
RUN npm install --ignore-scripts

# Build all workspaces
RUN npm run build

# The MCP server uses stdio, so no ports are exposed.

CMD ["node", "src/everything/dist/index.js"]
